// RSS feed config — keys must match news_sources.name in the DB for bias enrichment.
// defaultBias/defaultType are used as fallbacks when the DB table is empty.
export const RSS_SOURCES = [
  {
    key: 'rnz',
    displayName: 'RNZ',
    newsSourcesName: 'RNZ (Radio New Zealand)',
    rssUrl: 'https://www.rnz.co.nz/rss/political.xml',
    hasPaywall: false,
    defaultBias: 'centre',
    defaultType: 'news',
    defaultValidity: 'high',
    defaultPlatforms: ['web', 'podcast'],
  },
  {
    key: 'newsroom',
    displayName: 'Newsroom',
    newsSourcesName: 'Newsroom NZ',
    rssUrl: 'https://newsroom.co.nz/feed',
    hasPaywall: 'partial',
    defaultBias: 'centre-left',
    defaultType: 'news',
    defaultValidity: 'high',
    defaultPlatforms: ['web'],
  },
  {
    key: 'spinoff',
    displayName: 'The Spinoff',
    newsSourcesName: 'The Spinoff',
    rssUrl: 'https://thespinoff.co.nz/feed',
    hasPaywall: false,
    defaultBias: 'centre-left',
    defaultType: 'news',
    defaultValidity: 'medium',
    defaultPlatforms: ['web'],
  },
  {
    key: 'kiwiblog',
    displayName: 'Kiwiblog',
    newsSourcesName: 'Kiwiblog',
    rssUrl: 'https://www.kiwiblog.co.nz/feed',
    hasPaywall: false,
    defaultBias: 'right',
    defaultType: 'blog',
    defaultValidity: 'medium',
    defaultPlatforms: ['web'],
  },
  {
    key: 'the-standard',
    displayName: 'The Standard',
    newsSourcesName: 'The Standard',
    rssUrl: 'https://thestandard.org.nz/feed',
    hasPaywall: false,
    defaultBias: 'left',
    defaultType: 'blog',
    defaultValidity: 'medium',
    defaultPlatforms: ['web'],
  },
  {
    key: 'daily-blog',
    displayName: 'The Daily Blog',
    newsSourcesName: 'The Daily Blog',
    rssUrl: 'https://thedailyblog.co.nz/feed',
    hasPaywall: false,
    defaultBias: 'left',
    defaultType: 'blog',
    defaultValidity: 'medium',
    defaultPlatforms: ['web'],
  },
];

export const RSS_SOURCE_BY_KEY = Object.fromEntries(RSS_SOURCES.map((s) => [s.key, s]));
export const RSS_SOURCE_BY_DISPLAY_NAME = Object.fromEntries(RSS_SOURCES.map((s) => [s.displayName, s]));
